### ISSUE TITLE
Valid configs fail if fields missing

### ISSUE THREAD

**Issue by goddenrich** [kubernetes-client/python-base#162]
eg. get 
```
kube_config.py", line 587, in load_config
    self._merge(item, config[item], path)
KeyError: 'clusters'
```
for the example config from the k8s documentation https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/ 
```
contexts:
- context:
    cluster: development
    namespace: frontend
    user: developer
  name: dev-frontend
- context:
    cluster: development
    namespace: ramp
    user: developer
  name: dev-ramp-up
- context:
    cluster: development
    namespace: storage
    user: developer
  name: dev-storage
- context:
    cluster: scratch
    namespace: default
    user: experimenter
  name: exp-scratch
```
